name: Build dashboard payload

on:
  schedule:
    - cron: '0 */2 * * *' # every 2 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Build latest.json
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          TE_API_KEY: ${{ secrets.TE_API_KEY }}
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
        run: |
          python build_latest.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add public/latest.json
          git commit -m "Update dashboard payload" || echo "No changes"
          git push
